### ISSUE TITLE
Some usability suggestions

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/arloesiadur_industry_dataviz#24]
This is great! Only a bit of polish left:

In the map
Need to explain what is the meaning of "Score" in the map tooltips (is this local economic complexity?)

In the bubble-chart: 

-Number of businesses is a % (I assume). do *100 and add (%). Same with business growth (I assume it is a percentage too?)

-Add a legend for colours and sizes. 

-The current palette looks nice but I am a bit concerned that it suggests qualitative differences (red vs green vs blue) rather than a gradient in the probability distribution. I think that red vs blue with grey in 0.5, and a black edge-colour to make sure that sectors in the middle of the distribution are visible might work better but this is one of those try and see what works situations.

-Round up all numbers to 2 decimals.

-Indicate that it is possible to use click and drag to zoom in different areas of the bubble chart.

-Add legend at the bottom including links to ONS, blog and GitHub.

And I think that's it - great work!

**Comment by JamesGardiner** [comment]
Thanks! I'll split these into separate issues to track and close this one.

Note that I've just pushed  b96065e43e2b090df which updates the 'Number of businesses' value (I was using the proportions in error here). I'll push to Heroku shortly.

Business growth is a %; I'll update accordingly.

I assume that when you say legend for colours, you are referring to the map?

I agree with you on the palette. I'll try your suggested colours.

All the other points are no-problem.

**Comment by Juan-Mateos** [comment]
Sorry for not adding these individually! When I say legend, I refer to the map, but also to the colours in the bubble-chart bubbles.

**Comment by Juan-Mateos** [comment]
Sorry for not adding these individually! When I say legend, I refer to the map, but also to the colours in the bubble-chart bubbles.
